sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
    advertise: true
version:
  fromSource: pom.xml
linkReplacements:
  - "https://jdbc.postgresql.org/about/license.html|https://jdbc.postgresql.org/license/"
