sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - udf_coverage
      - jar_artifact
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.34.0"
    # - "7.1.30" # Exasol 7.1.x does not support the latest Ubuntu version
linkReplacements:
  - "https://jdbc.postgresql.org/about/license.html|https://jdbc.postgresql.org/license/"
