package com.exasol.adapter.dialects.postgresql.docgeneration;

import com.exasol.adapter.dialects.postgresql.PostgreSQLSqlDialectFactory;
import com.exasol.autogeneratedresourceverifier.AutogeneratedResourceVerifier;

public class PostgresAutogeneratedResourceVerifier {

    public static void main(final String[] args) {
        new AutogeneratedResourceVerifier().verifyResource(new CapabilitiesReport(new PostgreSQLSqlDialectFactory()));
    }
}
